import type { Metadata } from "next";
import { ReduxProvider } from "@/utils/ReduxProvider";
import Navbar from "@/component/ui/navbar/Navbar";
import { Footer } from "@/component/ui/footer/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ReduxProvider>{children}</ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
